//
//  MockScreen+ReportPDF.swift
//  coderpad
//
//  Generated one-page PDF for Screen report downloads, including export-option
//  markers for mock fidelity tests (#136).
//

import CoreGraphics
import CoreText
import Foundation

nonisolated extension MockScreenFixtures {
    /// A one-page PDF for the report download, drawn with Core Graphics so it's always a
    /// valid document that opens in Preview. Generated off the main thread (it runs on
    /// the URL loading system's threads), which Core Graphics PDF contexts support.
    /// Optional report flags mirror the live export query parameters (#136).
    static func reportPDF(
        candidate: String,
        score: Double?,
        reportType: String = "full",
        includeRank: Bool = false,
        comparativeScore: Double? = nil
    ) -> Data {
        let pdfData = NSMutableData()
        var mediaBox = CGRect(x: 0, y: 0, width: 420, height: 300)
        // ASCII info dictionary fields keep options inspectable in the raw PDF bytes
        // for mock fidelity tests (#136).
        var info: [CFString: String] = [
            kCGPDFContextTitle: "Candidate: \(candidate)",
            kCGPDFContextSubject: "Report type: \(reportType)"
        ]
        if includeRank {
            info[kCGPDFContextKeywords] = "Rank included"
        }
        if let comparativeScore {
            info[kCGPDFContextAuthor] = "Comparative score: \(Int(comparativeScore.rounded()))"
        }
        guard let consumer = CGDataConsumer(data: pdfData as CFMutableData),
              let context = CGContext(consumer: consumer, mediaBox: &mediaBox, info as CFDictionary) else {
            return Data()
        }

        context.beginPDFPage(nil)
        context.setFillColor(CGColor(red: 0.1, green: 0.1, blue: 0.12, alpha: 1))
        draw("CoderPad Screen: Demo Report", in: context, originX: 30, originY: 240, font: ReportFonts.title)
        draw("Candidate: \(candidate)", in: context, originX: 30, originY: 198, font: ReportFonts.body)
        draw("Report type: \(reportType)", in: context, originX: 30, originY: 176, font: ReportFonts.caption)
        if let score {
            draw(
                "Overall score: \(Int(score.rounded()))/100",
                in: context, originX: 30, originY: 150, font: ReportFonts.body
            )
        }
        if includeRank {
            draw("Rank included", in: context, originX: 30, originY: 128, font: ReportFonts.caption)
        }
        if let comparativeScore {
            draw(
                "Comparative score: \(Int(comparativeScore.rounded()))",
                in: context, originX: 30, originY: 110, font: ReportFonts.caption
            )
        }
        context.setFillColor(CGColor(red: 0.4, green: 0.4, blue: 0.42, alpha: 1))
        draw(
            "Sample report data generated by the in-app demo.",
            in: context, originX: 30, originY: 80, font: ReportFonts.caption
        )
        context.endPDFPage()
        context.closePDF()

        // Trailing ASCII markers keep export options inspectable in raw bytes for
        // mock fidelity tests; Core Text text runs are not reliably UTF-8 (#136).
        var marked = pdfData as Data
        var marker = "% mock-report candidate=\(candidate); type=\(reportType)"
        if includeRank { marker += "; rank=included" }
        if let comparativeScore {
            marker += "; comparative=\(Int(comparativeScore.rounded()))"
        }
        marked.append(contentsOf: Data("\n\(marker)\n".utf8))
        return marked
    }

    /// The three text sizes the report uses, resolved once instead of asking Core Text
    /// for the same Helvetica face on every line drawn (#2123). A `CTFont` is immutable
    /// once created, so sharing these across the URL-loading threads that generate the
    /// PDF is safe.
    private enum ReportFonts {
        nonisolated(unsafe) static let title = CTFontCreateWithName("Helvetica" as CFString, 20, nil)
        nonisolated(unsafe) static let body = CTFontCreateWithName("Helvetica" as CFString, 14, nil)
        nonisolated(unsafe) static let caption = CTFontCreateWithName("Helvetica" as CFString, 11, nil)
    }

    /// Draws a single line of text at a baseline point, using the context's current fill
    /// color (Core Text falls back to it when no foreground-color attribute is set).
    private static func draw(_ string: String, in context: CGContext,
                             originX: CGFloat, originY: CGFloat, font: CTFont) {
        let attributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key(kCTFontAttributeName as String): font
        ]
        let attributed = NSAttributedString(string: string, attributes: attributes)
        let line = CTLineCreateWithAttributedString(attributed)
        context.textPosition = CGPoint(x: originX, y: originY)
        CTLineDraw(line, context)
    }
}
