//
//  MockScreen+ReportPDF.swift
//  coderpad
//
//  Generated one-page PDF used by the Screen mock's report download endpoint.
//

import CoreGraphics
import CoreText
import Foundation

nonisolated extension MockScreenFixtures {
    /// A one-page PDF for the report download, drawn with Core Graphics so it's always a
    /// valid document that opens in Preview. Generated off the main thread (it runs on
    /// the URL loading system's threads), which Core Graphics PDF contexts support.
    ///
    /// Export options (#136): `candidate` is omitted when anonymous; comparative score
    /// and rank lines appear only when requested; `simplified` drops the caption detail.
    static func reportPDF(
        candidate: String?,
        score: Double?,
        comparativeScore: Double? = nil,
        rank: String? = nil,
        reportType: String = "full"
    ) -> Data {
        let pdfData = NSMutableData()
        var mediaBox = CGRect(x: 0, y: 0, width: 420, height: 300)
        let title = reportType == "simplified"
            ? "CoderPad Screen: Simplified Report"
            : "CoderPad Screen: Demo Report"
        var info: [CFString: Any] = [
            kCGPDFContextTitle: title,
            kCGPDFContextAuthor: candidate ?? "Anonymous",
            kCGPDFContextCreator: "CoderPadKitMock"
        ]
        var keywords: [String] = ["report_type=\(reportType)"]
        if let comparativeScore {
            keywords.append("comparative=\(Int(comparativeScore.rounded()))")
        }
        if let rank {
            keywords.append("rank=\(rank)")
        }
        info[kCGPDFContextKeywords] = keywords.joined(separator: ", ")

        guard let consumer = CGDataConsumer(data: pdfData as CFMutableData),
              let context = CGContext(
                consumer: consumer,
                mediaBox: &mediaBox,
                info as CFDictionary
              ) else {
            return Data()
        }
        context.beginPDFPage(nil)
        context.setFillColor(CGColor(red: 0.1, green: 0.1, blue: 0.12, alpha: 1))
        draw(title, in: context, originX: 30, originY: 240, font: ReportFonts.title)
        var cursorY: CGFloat = 198
        if let candidate {
            draw("Candidate: \(candidate)", in: context, originX: 30, originY: cursorY, font: ReportFonts.body)
            cursorY -= 28
        } else {
            draw("Candidate: Anonymous", in: context, originX: 30, originY: cursorY, font: ReportFonts.body)
            cursorY -= 28
        }
        if let score {
            draw(
                "Overall score: \(Int(score.rounded()))/100",
                in: context, originX: 30, originY: cursorY, font: ReportFonts.body
            )
            cursorY -= 28
        }
        if let comparativeScore {
            draw(
                "Comparative score: \(Int(comparativeScore.rounded()))",
                in: context, originX: 30, originY: cursorY, font: ReportFonts.body
            )
            cursorY -= 28
        }
        if let rank {
            draw("Rank: \(rank)", in: context, originX: 30, originY: cursorY, font: ReportFonts.body)
            cursorY -= 28
        }
        if reportType != "simplified" {
            context.setFillColor(CGColor(red: 0.4, green: 0.4, blue: 0.42, alpha: 1))
            draw(
                "Sample report data generated by the in-app demo.",
                in: context, originX: 30, originY: min(cursorY, 120), font: ReportFonts.caption
            )
        }
        context.endPDFPage()
        context.closePDF()
        return pdfData as Data
    }

    /// The three text sizes the report uses, resolved once instead of asking Core Text
    /// for the same Helvetica face on every line drawn (#2123). A `CTFont` is immutable
    /// once created, so sharing these across the URL-loading threads that generate the
    /// PDF is safe.
    private enum ReportFonts {
        nonisolated(unsafe) static let title = CTFontCreateWithName("Helvetica" as CFString, 20, nil)
        nonisolated(unsafe) static let body = CTFontCreateWithName("Helvetica" as CFString, 14, nil)
        nonisolated(unsafe) static let caption = CTFontCreateWithName("Helvetica" as CFString, 11, nil)
    }

    /// Draws a single line of text at a baseline point, using the context's current fill
    /// color (Core Text falls back to it when no foreground-color attribute is set).
    private static func draw(_ string: String, in context: CGContext,
                             originX: CGFloat, originY: CGFloat, font: CTFont) {
        let attributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key(kCTFontAttributeName as String): font
        ]
        let attributed = NSAttributedString(string: string, attributes: attributes)
        let line = CTLineCreateWithAttributedString(attributed)
        context.textPosition = CGPoint(x: originX, y: originY)
        CTLineDraw(line, context)
    }
}
